import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MenuContext from "@/context/MenuContext";
import MenuProvider from "@/context/MenuProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <MenuProvider>
        <body className={inter.className}>{children}</body>
      </MenuProvider>
    </html>
  );
}
